---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: robertdebock.postgres
      postgres_port: 6543
      postgres_databases:
        - name: test
      postgres_users:
        - name: test
          password: test
          db: test
